# Generated by Django 4.1.7 on 2023-03-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownermodel',
            old_name='manager_number',
            new_name='owner_id',
        ),
    ]
