# Generated by Django 4.1.7 on 2023-03-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('owners', '0002_rename_manager_number_ownermodel_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='owners.ownermodel')),
                ('ownerManagers', models.ManyToManyField(blank=True, default=None, related_name='owner_managers', to='managers.managermodel')),
            ],
        ),
    ]
