# Generated by Django 4.1.7 on 2023-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('owners', '0003_ownermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='management',
            field=models.ManyToManyField(blank=True, default=None, related_name='management', to='managers.managermodel'),
        ),
    ]
