# Generated by Django 4.1.7 on 2023-03-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('applications', '0001_initial'),
        ('owners', '0004_ownermodel_management'),
        ('property', '0003_availabilitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_number', models.CharField(blank=True, max_length=200, null=True)),
                ('propertyName', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('bedrooms', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=10)),
                ('garage', models.CharField(blank=True, max_length=200, null=True)),
                ('Floor_Size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Erf_Size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(blank=True)),
                ('Furnished', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=200, null=True)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('availability', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_availability', to='property.availabilitymodel')),
                ('eletricity_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eletricity_type', to='property.eletricitymodel')),
                ('managers', models.ManyToManyField(blank=True, default=None, related_name='property_managers', to='managers.managermodel')),
                ('owners', models.ManyToManyField(blank=True, default=None, related_name='property_owner', to='owners.ownermodel')),
                ('property_applications', models.ManyToManyField(blank=True, default=None, related_name='property_applicants', to='applications.applicationmodel')),
                ('property_features', models.ManyToManyField(blank=True, default=None, related_name='property_features', to='property.propertyfeatures')),
                ('property_for', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_is_for', to='property.propertyformodel')),
                ('property_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='property.propertytypemodel')),
            ],
        ),
    ]
