# Generated by Django 4.1.7 on 2023-03-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertymodel_property_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymodel',
            old_name='property_features',
            new_name='features_property',
        ),
    ]
