# Generated by Django 4.1.7 on 2023-03-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('property', '0006_rename_property_features_propertymodel_features_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in', models.DateField()),
                ('move_out', models.DateField()),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paydate', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='Tenant', max_length=200, null=True)),
                ('applicationstatus', models.CharField(blank=True, default='Approved', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_tenant', to='applications.applicationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='tenants',
            field=models.ManyToManyField(blank=True, default=None, related_name='listing_tenants', to='property.propertytenant'),
        ),
    ]
