# Generated by Django 4.1.7 on 2023-03-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('property', '0007_propertytenant_propertymodel_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_payment_policiy', models.TextField(blank=True, null=True)),
                ('utilities', models.TextField(blank=True, null=True)),
                ('maintenance_responsibilities', models.TextField(blank=True, null=True)),
                ('renewal_options', models.TextField(blank=True, null=True)),
                ('subletting_policy', models.TextField(blank=True, null=True)),
                ('pet_policy', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Tenant', max_length=200, null=True)),
                ('application_status', models.CharField(blank=True, default='Approved', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Property', to='property.propertymodel')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tenant', to='applications.applicationmodel')),
            ],
        ),
    ]
