# Generated by Django 4.1.7 on 2023-04-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('property', '0008_leasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='property_tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moved_in_tenant', to='applications.applicationmodel'),
        ),
    ]
