# Generated by Django 4.1.7 on 2023-04-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_propertymodel_property_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_date', models.DateField()),
                ('viewing_time', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Showing_Property', to='property.propertymodel')),
            ],
        ),
    ]
