# Generated by Django 4.1.7 on 2023-04-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('Vendors', '0001_initial'),
        ('Financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_expense', to='applications.applicationmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_expense', to='Vendors.vendormodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_income', to='applications.applicationmodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_income', to='Vendors.vendormodel'),
        ),
    ]
