# Generated by Django 4.1.7 on 2023-04-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('managers', '0001_initial'),
        ('Vendors', '0001_initial'),
        ('owners', '0004_ownermodel_management'),
        ('property', '0008_leasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.ManyToManyField(blank=True, default=None, related_name='Applicant', to='applications.applicationmodel')),
                ('inspector', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inspector', to='managers.managermodel')),
                ('managers', models.ManyToManyField(blank=True, default=None, related_name='Manager', to='managers.managermodel')),
                ('owners', models.ManyToManyField(blank=True, default=None, related_name='Owner', to='owners.ownermodel')),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Property_inspection', to='property.propertymodel')),
                ('vendors', models.ManyToManyField(blank=True, default=None, related_name='Vendor', to='Vendors.vendormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('inspection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inspection', to='Inspection.inspectionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='Inspection.itemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='Inspection.roommodel'),
        ),
    ]
