# Generated by Django 4.1.7 on 2023-04-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
