# Generated by Django 4.1.7 on 2023-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection', '0002_rename_image_photomodel_image1_photomodel_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspectionmodel',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
