# Generated by Django 4.1.7 on 2023-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection', '0003_roommodel_comments_alter_inspectionmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='inspection',
        ),
        migrations.AddField(
            model_name='roommodel',
            name='inspectionID',
            field=models.ManyToManyField(blank=True, default=None, related_name='Inspection_id', to='Inspection.inspectionmodel'),
        ),
    ]
